apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fe
  labels:
    app: nodejs
    tier: {{ .Release.Name }}-fe
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
    name: {{ .Release.Name }}-fe
  type: {{ .Values.frontend.service.typeService }}
  selector:
    app: nodejs
    tier: {{ .Release.Name }}-fe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fe
  labels:
    app: nodejs
    tier: {{ .Release.Name }}-fe
spec:
  selector:
    matchLabels:
      app: nodejs
      tier: {{ .Release.Name }}-fe
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        app: nodejs
        tier: {{ .Release.Name }}-fe
    spec:
      containers:
      - name: {{ .Release.Name }}-fe
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tags }}
        ports:
        - containerPort: 80
